/**
 * lib/i18n-telegram.ts
 *
 * Localized strings + language detection for the Telegram adapter's
 * acknowledgment + live status updates.
 *
 * Supported languages: English (en), Spanish (es), Simplified Chinese (zh).
 * Anything else falls back to English.
 *
 * Detection cascade (in order):
 *   1. Script-based short-circuits that are objectively correct — any
 *      CJK ideograph means zh, any of ñ/¿/¡ means es. These win
 *      unconditionally because the code points never appear in our other
 *      supported languages.
 *   2. For text long enough to be statistically meaningful (~12 chars),
 *      delegate to the `tinyld` library — a pure-JS port of Google's CLD
 *      with zero runtime deps. Covers the long-tail of phrasings without
 *      us maintaining a stopword list.
 *   3. For very short text that tinyld cannot disambiguate confidently
 *      (single greetings like "hola", "gracias"), check against a small
 *      curated set of the most common Spanish chat openings. Kept tiny
 *      on purpose — this is a last-resort edge case, not the primary
 *      detection path.
 *   4. Default to English.
 *
 * Misclassification is acceptable because the only user-visible localized
 * text is the ack line, tool-step labels, and a done footer. The final
 * agent response is generated by the LLM in the user's actual language,
 * so a wrong heuristic just means the ack is slightly off — never the
 * final answer.
 */

import { detect as tinyldDetect } from 'tinyld';

export type Lang = 'en' | 'es' | 'zh';

// Any CJK ideograph → Chinese. The range covers the CJK Unified Ideographs
// block used by both Simplified and Traditional Chinese (and Japanese kanji,
// but we only advertise zh here).
const CJK_RE = /[\u4e00-\u9fff]/;

// Characters that appear essentially only in Spanish among our supported
// languages. ñ is Spanish + Basque/Catalan/etc., ¿/¡ are Spanish-only.
const SPANISH_ONLY_CHARS_RE = /[ñ¿¡]/i;

// Short-text disambiguation fallback for things tinyld confuses with other
// Romance languages (e.g., "hola amigo" → pt). Intentionally small — keep
// it under ~20 entries and only add phrases that are unambiguous greetings
// or extremely common chat openings.
const SPANISH_SHORT_PHRASES: ReadonlySet<string> = new Set([
  'hola',
  'hola amigo',
  'gracias',
  'de nada',
  'por favor',
  'buenos días',
  'buenos dias',
  'buenas tardes',
  'buenas noches',
  'qué tal',
  'que tal',
  'cómo estás',
  'como estas',
  'hasta luego',
  'adiós',
  'adios',
]);

const TINYLD_MIN_LENGTH = 12;

export function detectLanguage(text: string): Lang {
  if (!text) return 'en';
  const trimmed = text.trim();
  if (!trimmed) return 'en';

  // 1. Scripts — unconditional.
  if (CJK_RE.test(trimmed)) return 'zh';
  if (SPANISH_ONLY_CHARS_RE.test(trimmed)) return 'es';

  // 2. tinyld for anything long enough to be meaningful.
  if (trimmed.length >= TINYLD_MIN_LENGTH) {
    const guess = tinyldDetect(trimmed);
    if (guess === 'es' || guess === 'en' || guess === 'zh') return guess;
    // tinyld returned a language we do not support (fr/de/pt/it/...) or
    // an empty string. Fall through to the default.
    return 'en';
  }

  // 3. Short-text Spanish greeting fallback.
  if (SPANISH_SHORT_PHRASES.has(trimmed.toLowerCase())) return 'es';

  // 4. Default.
  return 'en';
}

// ── Acknowledgment line ────────────────────────────────────────────────────

const ACK: Record<Lang, string> = {
  en: "Got it — give me a moment, I'm working on this.",
  es: 'Entendido, dame un momento que estoy trabajando en esto.',
  zh: '收到,请稍等,我正在处理。',
};

export function ackText(lang: Lang): string {
  return ACK[lang];
}

// ── "Done" footer when finalizing the live status message ──────────────────

export function doneText(lang: Lang, durationSec: number, stepCount: number): string {
  const sec = Math.max(1, Math.round(durationSec));
  switch (lang) {
    case 'es':
      return `✓ Hecho en ${sec}s · ${stepCount} ${stepCount === 1 ? 'paso' : 'pasos'}`;
    case 'zh':
      return `✓ 完成,用时 ${sec} 秒 · ${stepCount} 步`;
    case 'en':
    default:
      return `✓ Done in ${sec}s · ${stepCount} ${stepCount === 1 ? 'step' : 'steps'}`;
  }
}

// ── Tool-call labels for the live status updates ────────────────────────────

const TOOL_LABELS: Record<string, Record<Lang, string>> = {
  web_search:       { en: '🔍 Searching the web',     es: '🔍 Buscando en la web',     zh: '🔍 网络搜索' },
  browser:          { en: '🌐 Browsing',               es: '🌐 Navegando',              zh: '🌐 浏览网页' },
  recall_history:   { en: '📚 Recalling history',      es: '📚 Recordando historial',    zh: '📚 查询历史' },
  write:            { en: '✍️ Writing',                es: '✍️ Escribiendo',            zh: '✍️ 写入文件' },
  read:             { en: '📖 Reading',                es: '📖 Leyendo',                zh: '📖 读取文件' },
  bash:             { en: '⚙️ Running command',        es: '⚙️ Ejecutando comando',     zh: '⚙️ 执行命令' },
  list_tasks:       { en: '📋 Listing tasks',          es: '📋 Listando tareas',        zh: '📋 列出任务' },
  get_task:         { en: '📋 Reading task',           es: '📋 Leyendo tarea',          zh: '📋 查看任务' },
  create_task:      { en: '📋 Creating task',          es: '📋 Creando tarea',          zh: '📋 创建任务' },
  update_task:      { en: '📋 Updating task',          es: '📋 Actualizando tarea',     zh: '📋 更新任务' },
  add_task_comment: { en: '💬 Adding comment',         es: '💬 Añadiendo comentario',   zh: '💬 添加评论' },
};

const FALLBACK: Record<Lang, (toolName: string) => string> = {
  en: (t) => `⚙️ Using ${t}`,
  es: (t) => `⚙️ Usando ${t}`,
  zh: (t) => `⚙️ 使用 ${t}`,
};

export function toolLabel(lang: Lang, toolName: string): string {
  const entry = TOOL_LABELS[toolName];
  if (entry) return entry[lang];
  return FALLBACK[lang](toolName);
}

// ── "(N more steps)" summary when the live message gets too long ───────────

export function moreStepsSuffix(lang: Lang, n: number): string {
  switch (lang) {
    case 'es':
      return `(${n} ${n === 1 ? 'paso más' : 'pasos más'})`;
    case 'zh':
      return `(还有 ${n} 步)`;
    case 'en':
    default:
      return `(${n} more ${n === 1 ? 'step' : 'steps'})`;
  }
}
