/**
 * lib/i18n-telegram.ts
 *
 * Localized strings + cheap language detection for the Telegram adapter's
 * acknowledgment + live status updates.
 *
 * Supported languages: English (en), Spanish (es), Simplified Chinese (zh).
 * Anything else falls back to English.
 *
 * Detection is intentionally heuristic — no ML, no library, no LLM call:
 *   - zh wins if any CJK ideograph is present
 *   - es wins if Spanish-only characters (ñ, ¿, ¡) appear or common Spanish
 *     stopwords occur
 *   - en is the default
 *
 * Misclassification is OK because the only user-visible English text is the
 * ack and the tool-step labels. The final agent response is generated by the
 * LLM in the user's actual language, so a wrong heuristic just means the
 * acknowledgement is slightly off — never the final answer.
 */

export type Lang = 'en' | 'es' | 'zh';

const SPANISH_HINTS = [
  // Spanish-only chars
  /[ñ¿¡]/i,
  // Common stopwords / greetings, anchored on word boundaries
  /\b(hola|gracias|por favor|qué|cómo|cuándo|dónde|para|porque|también|esto|esta|este|tengo|necesito|quiero)\b/i,
  // Common verbs used in everyday requests
  /\b(busca|buscar|necesita|necesitas|hace|hacer|dame|dime|ayuda|ayudar|puedo|puede|puedes|tienes|sabes|quieres|mira|mirar|revisa|revisar|crea|crear|escribe|escribir|analiza|analizar|explica|explicar|encuentra|encontrar|muestra|mostrar|abre|abrir|deja|dejar|pon|poner|trae|traer|usa|usar)\b/i,
  // Common words that are Spanish-only or statistically dominant in Spanish
  /\b(favor|bien|información|informacion|todo|todos|ahora|aquí|aqui|hay|más|mas|pero|solo|muy|cuando|donde|como|cual|cuál|este|esa|ese|eso|algo|alguien|nada|nadie|siempre|nunca|también|tampoco|después|despues|antes|durante|mientras|entonces|luego|además|ademas|sobre|entre|contra|hacia|desde|hasta|mediante|según|segun)\b/i,
  // Common greetings / closings not already covered
  /\b(buenos|buenas|hasta|hoy|mañana|manana|semana|mes|año|anio|lunes|martes|miércoles|miercoles|jueves|viernes|sábado|sabado|domingo)\b/i,
];

const CHINESE_RE = /[\u4e00-\u9fff]/;

export function detectLanguage(text: string): Lang {
  if (!text) return 'en';
  if (CHINESE_RE.test(text)) return 'zh';
  for (const re of SPANISH_HINTS) {
    if (re.test(text)) return 'es';
  }
  return 'en';
}

// ── Acknowledgment line ────────────────────────────────────────────────────

const ACK: Record<Lang, string> = {
  en: "Got it — give me a moment, I'm working on this.",
  es: 'Entendido, dame un momento que estoy trabajando en esto.',
  zh: '收到,请稍等,我正在处理。',
};

export function ackText(lang: Lang): string {
  return ACK[lang];
}

// ── "Done" footer when finalizing the live status message ──────────────────

export function doneText(lang: Lang, durationSec: number, stepCount: number): string {
  const sec = Math.max(1, Math.round(durationSec));
  switch (lang) {
    case 'es':
      return `✓ Hecho en ${sec}s · ${stepCount} ${stepCount === 1 ? 'paso' : 'pasos'}`;
    case 'zh':
      return `✓ 完成,用时 ${sec} 秒 · ${stepCount} 步`;
    case 'en':
    default:
      return `✓ Done in ${sec}s · ${stepCount} ${stepCount === 1 ? 'step' : 'steps'}`;
  }
}

// ── Tool-call labels for the live status updates ────────────────────────────

const TOOL_LABELS: Record<string, Record<Lang, string>> = {
  web_search:       { en: '🔍 Searching the web',     es: '🔍 Buscando en la web',     zh: '🔍 网络搜索' },
  browser:          { en: '🌐 Browsing',               es: '🌐 Navegando',              zh: '🌐 浏览网页' },
  recall_history:   { en: '📚 Recalling history',      es: '📚 Recordando historial',    zh: '📚 查询历史' },
  write:            { en: '✍️ Writing',                es: '✍️ Escribiendo',            zh: '✍️ 写入文件' },
  read:             { en: '📖 Reading',                es: '📖 Leyendo',                zh: '📖 读取文件' },
  bash:             { en: '⚙️ Running command',        es: '⚙️ Ejecutando comando',     zh: '⚙️ 执行命令' },
  list_tasks:       { en: '📋 Listing tasks',          es: '📋 Listando tareas',        zh: '📋 列出任务' },
  get_task:         { en: '📋 Reading task',           es: '📋 Leyendo tarea',          zh: '📋 查看任务' },
  create_task:      { en: '📋 Creating task',          es: '📋 Creando tarea',          zh: '📋 创建任务' },
  update_task:      { en: '📋 Updating task',          es: '📋 Actualizando tarea',     zh: '📋 更新任务' },
  add_task_comment: { en: '💬 Adding comment',         es: '💬 Añadiendo comentario',   zh: '💬 添加评论' },
};

const FALLBACK: Record<Lang, (toolName: string) => string> = {
  en: (t) => `⚙️ Using ${t}`,
  es: (t) => `⚙️ Usando ${t}`,
  zh: (t) => `⚙️ 使用 ${t}`,
};

export function toolLabel(lang: Lang, toolName: string): string {
  const entry = TOOL_LABELS[toolName];
  if (entry) return entry[lang];
  return FALLBACK[lang](toolName);
}

// ── "(N more steps)" summary when the live message gets too long ───────────

export function moreStepsSuffix(lang: Lang, n: number): string {
  switch (lang) {
    case 'es':
      return `(${n} ${n === 1 ? 'paso más' : 'pasos más'})`;
    case 'zh':
      return `(还有 ${n} 步)`;
    case 'en':
    default:
      return `(${n} more ${n === 1 ? 'step' : 'steps'})`;
  }
}
